export { default as Home } from "./Home";
export { default as Products } from "./Products";
export { default as Inks } from "./Inks";
export { default as InkDetail } from "./InkDetail";
export { default as Printers } from "./Printers";
export { default as Services } from "./Services";
export { default as Supplies } from "./Supplies";
export { default as Checkout } from "./Checkout";
export { default as NotFound } from "./NotFound";